packaging_format = 2

id = "paheko"
name = "Paheko"
description.en = "Software to manage association"
description.fr = "Logiciel libre de gestion d'association"

version = "1.2.8~ynh1"

maintainers = ["rodinux"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://paheko.cloud"
demo = "https://paheko.cloud/essai/"
admindoc = "https://fossil.kd2.org/paheko/wiki?name=Documentation"
code = "https://fossil.kd2.org/paheko/dir?ci=tip"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/paheko"

    [install.init_main_permission]
    help.en = "The SSO is not implemented for this app and yunohost is not sure for hundred of users..."
    help.fr = "Le SSO n'est pas implémenté pour cette application et yunohost n'est pas sûr pour une centaine d'utilisateurs..."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://fossil.kd2.org/paheko/uv/paheko-1.2.8.tar.gz"
        sha256 = "d1946fca1a56b03fc59f577fe750aca2e94251a10440eea354b523d553ddd3fa"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-sqlite3 php8.0-gd php8.0-intl  php8.0-cli php8.0-gnupg"
