packaging_format = 2

id = "paheko"
name = "Paheko"
description.en = "Association management software"
description.fr = "Logiciel de gestion d'association"

version = "1.3.1~ynh1"

maintainers = ["rodinux"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://paheko.cloud"
demo = "https://paheko.cloud/essai/"
admindoc = "https://fossil.kd2.org/paheko/wiki?name=Documentation"
code = "https://fossil.kd2.org/paheko/dir?ci=tip"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/paheko"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://fossil.kd2.org/paheko/uv/paheko-1.3.1.tar.gz"
        sha256 = "0b82c47a084282db2b3df5737bc4834690ba5dc9d06e07512439487753b45ebb"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "wkhtmlopdf, mupdf-tools, sqlite3, php8.2-sqlite3, php8.2-gd, php8.2-intl, php8.2-cli, php8.2-gnupg, php8.2-mbstring, php8.2-zip"
