test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.534bb03f927c5301e69bc0339a7441142a75b485.name = "Upgrade from 1.2.8"
